# describe the activation workflow
type: Workflow
match:
  callback: exact_match
  input: "/search-issue"
key: jira_search_issue
---
type: Operation
is_root: true
selector:
  workflow:
    - jira_search_issue
  app: whatsapp
  app_action: send_message
next:
  selector:
    - type: operation
      data:
        workflow: jira_search_issue
        next: query_jira
payload:
  content:
    type: raw
    data: "What would you like me to search? 🧐\n(remember! this demo uses JQL syntax)\n **example:\nstatus='To Do'**"
key: get_query
---
type: Operation
selector:
  workflow:
    - jira_search_issue
  app: jira
  app_action: search_issue
on_error:
  selector:
    - type: operation
      data:
        workflow: jira_search_issue
        next: send_error_message
next:
  selector:
    - type: operation
      data:
        workflow: jira_search_issue
        next: send_success_message
payload:
  query:
    type: request
    data: message_data.message.body
key: query_jira
---
type: Operation
selector:
  workflow:
    - jira_search_issue
  app: whatsapp
  app_action: send_message
output:
  operation_type: drop_session
payload:
  content:
    type: redis
    data: query_jira:message
key: send_success_message
---
type: Operation
selector:
  workflow:
    - jira_search_issue
  app: whatsapp
  app_action: send_message
output:
  operation_type: drop_session
payload:
  content:
    type: raw
    data: "Something went wrong! 🤬\nYou can check your server logs so learn more..."
key: send_error_message
